### ISSUE TITLE
Parser always returns false as some AnalogyLogMessagePropertyName is not implemented in switch

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer.Log4Net#70]
In here:

https://github.com/Analogy-LogViewer/Analogy.LogViewer.Log4Net/blob/edc29369eb2e70f39eabe6b93e83a1f5e4e0ccdf/Analogy.LogViewer.Log4Net/RegexParser.cs#L341

There is a switch on `regexMember.Value` that will handle values differently depending on the "AnalogyLogMessagePropertyName", this method keeps returning false since the switch throws the ArgumentException when no switch applies.

Looks like these does not have a switch hence it will throw all the time

* AnalogyLogMessagePropertyName.MachineName
* AnalogyLogMessagePropertyName.RawText
* AnalogyLogMessagePropertyName.RawTextType

Adding them like this would solve it

```
case AnalogyLogMessagePropertyName.MachineName:
    m.MachineName = value;
    break;
case AnalogyLogMessagePropertyName.RawText:
    m.RawText = value;
    break;
case AnalogyLogMessagePropertyName.RawTextType:
    m.RawTextType = AnalogyRowTextType.PlainText;
    break;
```

But I think that the "right" solution is to not throw?

I would provide a PR with some unit test as well if wanted?

**Comment by LiorBanai** [comment]
Good catch 🙂
Yeah you can submit a pr. Thanks!

**Comment by enkelmedia** [comment]
I would also argue that `RegexOptions.IgnorePatternWhitespace` should be removed as some log formats might depend on whitespace and it's hard to create a regex for these when the whitespace is ignored.
 
 I can see that this is a breaking change, on the other hand at the moment everything is broken =D
 
 Can I remove the IgnorePatternWhitespace?

**Comment by LiorBanai** [comment]
Yeah we can add in the ui form some indication for this.

**Comment by enkelmedia** [comment]
I guess that it calls for another issue but it was quite hard to understand that the "Test" button tested the regex from the textbox and not all the patterns in the list. Might be room for improvements on that as well - but not sure how much effort that should be put into it =D

**Comment by LiorBanai** [comment]
yeah the ui could be improve to have 2 sections: 1 for testing input regex and one for test all the settings already added patterns. but once it was tested as pre added pattern it is not really necessary to retest as part of the settings themselves.

Thanks for all your fixes and changes. I'll all of them tomorrow :)
